<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-V1TVAK6" name="Test" tests="2" failures="1" timestamp="27 Aug 2023 16:22:09 GMT" time="34.002" errors="0">
  <testcase name="test1" time="6.004" classname="org.reg.DemoReg"/>
  <testcase name="test2" time="9.711" classname="org.reg.DemoReg">
    <failure type="java.lang.AssertionError" message="expected [suganya.iniya23@gmail.com] but found [suganya.iniya@gmail.com]">
      <![CDATA[java.lang.AssertionError: expected [suganya.iniya23@gmail.com] but found [suganya.iniya@gmail.com]
	at org.reg.DemoReg.test2(DemoReg.java:52)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- Test -->
